### ISSUE TITLE
Suggestion: create CSS style rules from inline style="style: rule"

### ISSUE THREAD

**Issue by strativd** [ardcore/atom-html-to-css#1]
Maybe there's a package that already does this, not sure (I'm new to Atom!).

But it would be awesome if this add-on automatically generated CSS based on any inline style rules.

So for something like this:
`<div class="auto-style" style="margin: 10px 0px; color: #fff; background-color: #222;">`

The add-on automatically generated this:
`.auto-style {
  margin: 10px 0px;
  color: #fff;
  background-color: #222;
}`

Just an idea :)

**Comment by ardcore** [comment]
Thanks for the feedback. While I can imagine situations when this would be useful (legacy code, mostly), I think it is beyond the scope of this package.
